name: Update GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  workflow_dispatch:

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io jq

    - name: Run metrics action
      run: |
        echo "GitHub action: $METRICS_ACTION ($METRICS_ACTION_PATH)"
        cd $METRICS_ACTION_PATH
        for DEPENDENCY in docker jq; do
          if ! which $DEPENDENCY > /dev/null 2>&1; then
            echo "::error::$DEPENDENCY is not installed on current runner but is needed to run metrics"
            exit 1
          fi
        done
        METRICS_IMAGE=ghcr.io/lowlighter/metrics:$METRICS_TAG
        echo "Using pre-built version $METRICS_TAG, will pull docker image from GitHub registry"
        if ! docker image pull $METRICS_IMAGE; then
          echo "Failed to fetch docker image from GitHub registry, will rebuild it locally"
          METRICS_IMAGE=metrics:$METRICS_VERSION
        fi
        node index.mjs
